import { createSlice } from "@reduxjs/toolkit";

const initialState = {
	movies: [
		{
			id: 0,
			title: "Very Strange Things",
			season: "1 2 3 4 5",
			img: "trange-things.png",
			category: ["all", "fantastic", "horror"],
			description:
				"1980s, a quiet provincial American town. The favorable course of local life is disrupted by the mysterious disappearance of a teenager named Will. The boy's relatives and the local sheriff are determined to find out the circumstances of the case, and the events also affect Will's best friend, Mike. He starts his own investigation. Mike is sure that he is close to the solution, and now he has to find himself in the epicenter of a fierce battle of otherworldly forces.",
			trailer: "https://youtu.be/b9EkMc79ZSU?si=2eqCKhcEH3E76LKz",
			imgTrailer: "imgTrailer-strange_things.png",
			premiere: "15 July's 2016",
			director: "Matt Differentiation",
			music: "Kyle Dixon & Michael Stein",
			background: "bacg-strange_things.jpg",
		},
		{
			id: 1,
			title: "Black Mirror",
			season: "1 2 3 4 5 6",
			img: "black-mirror.png",
			category: ["all", "detective", "horror"],
			description: `Black Mirror is a British fantasy series, a modern analogue of the classic series "The Outer Limits". It shows the life of pathetic little people spoiled by high technology in the near future. Raises questions of morality and morality. The trick of the series is an hour and a half series.`,
			imgTrailer: "imgTrailer-black-mirror.png",
			trailer: "https://youtu.be/5jY1ecibLYo?si=uWViVzJa-RsWM7XR",
			premiere: "17 July's 2011",
			director: "Owen Harris, Carl Tibbetts, James Hawes",
			music: "Jon Opstad",
			background: "bacg-black-mirror.jpg",
		},
		{
			id: 2,
			title: "Love. Death. Robots.",
			season: "1 2 3 4",
			img: "Love.Death.Robots.png",
			category: ["all", "fantastic", "comedy", "cartoon"],
			description:
				"The series is built in the format of an anthology, in which each episode tells its own story, different from the others, with the participation of its own characters, and has a complete plot. Animated short films are shot in the genre of science fiction, cyberpunk, black humor and are designed for an adult audience. There is an erotic and brutal context here, the themes of racism, free will, the robotic future of humanity, and war are touched upon.",
			imgTrailer: "imgTrailer-love-death.png",
			trailer: "https://youtu.be/wUFwunMKa4E?si=VYS9bEGNJwHJdzBC",
			premiere: "15 March 2019",
			director: "Jerome Denjean",
			music: "Hans Zimmer",
			background: "bacg-love-death.jpg",
		},
		{
			id: 3,
			title: "Gravity Falls",
			season: "1 2",
			img: "Gravity-Falls.png",
			category: ["all", "fantastic", "comedy", "cartoon"],
			description:
				"The story tells about the adventures of twins, brother and sister Dipper and Mabel Pines, whose summer plans are sent to the closet when their parents send them to a distant relative in the quiet town of Gravity Falls. But is this city, relative and inhabitants so simple, and what secrets are waiting for their discoverers?",
			imgTrailer: "imgTrailer-gravity-falls.png",
			trailer: "https://youtu.be/yfUDIPUETUg?si=bUGh7_FOxpd8HySg",
			premiere: "14 June's 2012",
			director: "Joe Pitt, John Aoshima",
			music: "Brad Brekk",
			background: "bacg-gravity-falls.jpg",
		},
		{
			id: 4,
			title: "Inside job",
			season: "1 2",
			img: "Inside-job.png",
			category: ["all", "fantastic", "cartoon"],
			description: `For the workers of the "Deep State" conspiracy theories are not nonsense, but real facts. And their job is to keep it a secret.`,
			imgTrailer: "imgTrailer-inside-job.png",
			trailer: "https://youtu.be/-aZBIpZY_Fw?si=0JMQ0xpAvW7J1vIm",
			premiere: "22 October 2021",
			director: "Vitaly Strokous, David Fox",
			music: "Michael Stein",
			background: "bacg-inside-job.jpg",
		},
		{
			id: 5,
			title: "Moon Knight",
			season: "1",
			img: "Mocn-Knight.png",
			category: ["all", "fantastic", "action movie"],
			description: `Stephen Grant (Oscar Isaac) is a minor employee of the historical museum, suffering from periodic memory lapses and obvious self—doubt. Stephen is well versed in Egyptian mythology and quotes French poetry from memory, but when it comes to social skills, he has a hard time.`,
			imgTrailer: "imgTrailer-moon-knight.png",
			trailer: "https://youtu.be/x7Krla_UxRg?si=O8S2IESVORzYtGP9",
			premiere: "30 March 2022",
			director: "Mohamed Diab",
			music: "By Hesham Nazih",
			background: "bacg-moon-knight.jpg",
		},
		{
			id: 6,
			title: "The Simpsons",
			season: "1 2 3 4 5 6",
			img: "the-simpsons.jpg",
			category: ["all", "fantastic", "comedy", "cartoon", "new products"],
			description: `The animated series satirically shows the life of the Simpson family and other residents of the fictional town of Springfield, ridiculing many cliches and stereotypes, in particular, the lifestyle of the "average American", the peculiarities of world cultures in general, celebrities, and even television itself and the Fox TV channel.`,
			imgTrailer: "imgTrailer-the-simpsons.jpg",
			trailer: "https://youtu.be/l96zmDlWCBk?si=0SmWGNPrSBRCX5ZK",
			premiere: "14 June 2012",
			director: "Joe Pitt",
			music: "Rob Cairns",
			background: "bacg-simpsons.jpg",
			featuredImg: "the-simpsons.jpg",
		},
		{
			id: 7,
			title: "Rick and Morty",
			season: "1",
			img: "Rick-Morty.png",
			category: ["all", "fantastic", "cartoon", "new products", "comedy"],
			description:
				"The series is a supernatural detective comedy about growing up, dedicated to Wednesday Addams and her years when she was in high school at Nevermore Academy, where she tries to master her psychic abilities, stop a monstrous series of murders of citizens and solve a supernatural mystery that affected her family 25 years ago, and all this during her new relationship.",
			imgTrailer: "imgTrailer-rick-and-morty.png",
			trailer: "https://youtu.be/jerFRSQW9g8?si=W9tYSJKOXvCrhRTO",
			premiere: "31 October 2022",
			director: "Tim Burton, James Marshall",
			music: "Rob Cairns",
			background: "bacg-rick-and-morty.jpg",
			featuredImg: "rick-morty.jpg",
		},
		{
			id: 8,
			title: "Chainsaw Man",
			season: "1",
			img: "chainsaw_man.png",
			category: ["all", "fantastic", "Action Movie"],
			description: `Aki and Power become the partners of the Chainsaw Man. Soon the hero falls in love with a mysterious girl named Reza, who turns out to be a female bomb sent after him. Besides her, Denji is being hunted by several other groups of killers.`,
			imgTrailer: "imgTrailer-chainsaw_man.png",
			trailer: "https://youtu.be/l96zmDlWCBk?si=0SmWGNPrSBRCX5ZK",
			premiere: "11 October 2022",
			director: "Ryu Nakayama",
			music: "Kensuke Ushio",
			background: "bacg-chainsaw_man.jpg",
		},
		{
			id: 9,
			title: "Mr pickles",
			season: "1 2 3",
			img: "pickles.jpg",
			category: ["all", "horror", "comedy", "cartoon", "new products"],
			description: `An ordinary-looking Goodman family lives in an ordinary city, who dote on their pet, named Mr. Pickles. However, none of them knows that a dog with deviant behavior conducts satanic rituals at night and terrorizes all living things in the neighborhood in every possible way.`,
			imgTrailer: "imgTrailer-pickles.jpg",
			trailer: "https://youtu.be/l96zmDlWCBk?si=0SmWGNPrSBRCX5ZK",
			premiere: "21 September 2014",
			director: "Rizzo Eric Binns",
			music: "Rob Cairns",
			background: "bacg-pickles.jpg",
			featuredImg: "pickles.png",
		},
		{
			id: 10,
			title: "futurama",
			season: "1 2 3 4 5",
			img: "futurama.jpg",
			category: ["all", "comedy", "cartoon", "new products"],
			description: `By a ridiculous coincidence, Fry finds himself in the future — in the year 3000, where his faithful friends are waiting for him in the person of the mad robot Bender and the one-eyed Lila.`,
			imgTrailer: "imgTrailer-futurama.jpg",
			trailer: "https://youtu.be/l96zmDlWCBk?si=0SmWGNPrSBRCX5ZK",
			premiere: "21 September 2014",
			director: "Matt Groening",
			music: "White Rabbit",
			background: "bacg-futurama.jpg",
			featuredImg: "futurama.jpg",
		},
		{
			id: 11,
			title: "Super Jail",
			season: "1 2 3",
			img: "super-jail.jpg",
			category: ["all", "cartoon", "new products"],
			description: `The action of the animated series takes place in a high-security prison, which contains thousands of the most dangerous criminals. The structure itself is located inside a volcano, which, in turn, is located in another, larger volcano. From the inside, the "prison" is its own reality, in which space and time live according to their unnatural and even frightening laws, which change (but not always) at the whim of the eccentric chief Worden.`,
			imgTrailer: "imgTrailer-super-jail.jpg",
			trailer: "https://youtu.be/l96zmDlWCBk?si=0SmWGNPrSBRCX5ZK",
			premiere: "28 September 2008",
			director: "Christy Karacas",
			music: "Bradford Reed & Elmer Bernstein",
			background: "bacg-super-jail.jpg",
			featuredImg: "super-jail.jpg",
		},
		{
			id: 12,
			title: "Primal",
			season: "1 2 3",
			img: "primal.jpg",
			category: ["all", "horror", "new products"],
			description: `Prehistoric times. Almost becoming the dinner of a giant crocodile, primitive man returns from fishing to his native cave right at the moment when a pack of predatory dinosaurs eats his woman and children. Soon, an orphaned man unexpectedly joins forces with a tyrannosaurus trying unsuccessfully to protect the cubs from the same predators that killed his family.`,
			imgTrailer: "imgTrailer-primal.jpg",
			trailer: "https://youtu.be/l96zmDlWCBk?si=0SmWGNPrSBRCX5ZK",
			premiere: "8 October 2019",
			director: "Michael Lazzo",
			music: "Tyler Bates",
			background: "bacg-primal.jpg",
			featuredImg: "primal.jpg",
		},
		{
			id: 13,
			title: "American Dad",
			season: "1 2 3 5 6",
			img: "american-dad.jpg",
			category: ["all", "horror", "new products"],
			description: `The plot of the animated series revolves around the Smith family. Dad Stan is a CIA agent and a Republican to the core, strong in body, but stupid in mind. He has the manliest chin and always ironed suit. Francine is Stan's wife and the mother of the children. A typical housewife.`,
			imgTrailer: "imgTrailer-american-dad.jpg",
			trailer: "https://youtu.be/l96zmDlWCBk?si=0SmWGNPrSBRCX5ZK",
			premiere: "6 February 2005",
			director: "Seth MacFarlane, Mike Barker",
			music: "Kara Vallow",
			background: "bacg-american-dad.jpg",
			featuredImg: "american-dad.jpg",
		},
	],
};

const movieSlice = createSlice({
	name: "movies",
	initialState,
	reducers: {},
});

export default movieSlice.reducer;
